### PR TITLE
Fixed issues with compiling and few minor nitpicks

### PR DESCRIPTION
**Pull request by nopjmp**
Removed unneeded sections, removed deprecated functions and used a better for loop for deleteDir

I've tested this on my local machine and it works. We haven't put it onto a live system just yet, but we will be doing that shortly.

### CODE REVIEW

**Comment by nopjmp** [comment]
Not sure if needs a version bump since it didn't change behavior from the previously not working version.

**Comment by nopjmp** [comment]
We deployed this to one production machines that would occasionally lock up that I suspected was a race condition with the mod_cfml.dat. Now that file is no longer being used, I will see if we still run into that behavior. I'll make an issue on it if I'm able to make a reproducible case.

**Comment by utdream** [comment]
Hey Kyle,

Sorry it's taken me so long to look at this. There's a lot going on at Vivio these days. I looked over your changes and they look great. Thank you!

How did your new compile go in your production environment? Any issues? If no issues, could you go ahead and increment the version number and do a compile so that we can have a binary available for the public to use? I'll go ahead and do the merge once we have those two things in place.

Thank you for your help! This is why open-source is awesome!

-Jordan

**Comment by nopjmp** [comment]
We haven't found any problems in our production environment on Linux or Windows. I have some Apache modules changes I will create a pull request on this evening after my changes are merged. This fixes a long standing issue we had with contexts getting data races.

**Pull request closed without merging**
