### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by paulklinkenberg**
Hi Jordan, a small change in the compile instructions. Some users thought everyone needed to compile their own, while we have some compiled versions as well.

### CODE REVIEW

**Comment by utdream** [comment]
I did some system specific compiles here too:
https://github.com/utdream/CFML-Installers/tree/master/lucee/linux/sys/mod_cfml

Think those would be helpful?

**Comment by utdream** [comment]
The install_mod_cfml.sh script uses them when the installer is used on Linux systems:
https://github.com/utdream/CFML-Installers/blob/master/lucee/linux/sys/install_mod_cfml.sh

**Comment by paulklinkenberg** [comment]
Hi Jordan,

What would be the best way to link to those, in your opinion?
Maybe removing the 2 compiled versions from the mod_cfml repo, and adding a readme.md there, which links to the cfml-installers versions?

Kind regards,

Paul

Op 31 jul. 2015, om 01:51 heeft Jordan Michaels <notifications@github.com> het volgende geschreven:

I did some system specific compiles here too:
https://github.com/utdream/CFML-Installers/tree/master/lucee/linux/sys/mod_cfml <https://github.com/utdream/CFML-Installers/tree/master/lucee/linux/sys/mod_cfml>
Think those would be helpful?

**Comment by utdream** [comment]
Maybe just link to it in the readme from here? IE: "Compiled versions of the mod_cfml.so that are used in the Lucee installer are available by CLICKING HERE"... or something like that. It sounds easy to update and we don't have to move files around from different repos. Thoughts?

**Comment by paulklinkenberg** [comment]
See new pull request, and : http://www.modcfml.org/index.cfm/downloads/ <http://www.modcfml.org/index.cfm/downloads/>


Op 31 jul. 2015, om 20:03 heeft Jordan Michaels <notifications@github.com> het volgende geschreven:

Maybe just link to it in the readme from here? IE: "Compiled versions of the mod_cfml.so that are used in the Lucee installer are available by CLICKING HERE"... or something like that. It sounds easy to update and we don't have to move files around from different repos. Thoughts?

**Pull request merged**
